#!/bin/sh
# cpbasic - created with 'mkshcmd'
if [ "$1" = "--help" -o "$1" = "" ]; then
  echo "Copy BASIC command HELP file"
  echo " copies commands help NAME to new NEWNAME, then edit it"
  echo "usage: cpbasichelp NAME NEWNAME"
  echo "options:"
  echo "  NAME		required, must exist"
  echo "  NEWNAME	required, must not exist"
  exit 0
fi
if [ "$1" = "" -o "$2" = "" ]; then
  echo "Error: cpbasichelp NAME NEWNAME"
  exit 1
fi
if [ -f "${BASIC}x_HELP/$2" ]; then
  echo "Error: '$2' already exists"
  exit 2
fi
if [ ! -f "${BASIC}x_HELP/$1" ]; then
  echo "Error: '$1' does not exist"
  exit 3
fi
cp "${BASIC}x_HELP/$1" "${BASIC}x_HELP/$2"
if [ ! -x ~/bin/e ]; then
  echo "created: '$2'"
  echo "Error: 'ln -s _path_to_editor_ ~/bin/e' to set editor"
  exit 4
fi
e "${BASIC}x_HELP/$2"
exit 0
