#!/bin/sh
# cpbasic - created with 'mkshcmd'
if [ "$1" = "--help" -o "$1" = "" ]; then
  echo "Copy BASIC command"
  echo " copies command and its help to new command, then edit them"
  echo "usage: cpbasic COMMAND NEWCOMMAND"
  echo "options:"
  echo "  COMMAND	required, must exist"
  echo "  NEWCOMMAND	required, must not exist"
  exit 0
fi
if [ "$1" = "" -o "$2" = "" ]; then
  echo "Error: cpbasic COMMAND NEWCOMMAND"
  exit 1
fi
if [ -x "${BASIC}$2" ]; then
  echo "Error: '$2' already exists"
  exit 2
fi
if [ ! -x "${BASIC}$1" ]; then
  echo "Error: '$1' does not exist"
  exit 3
fi
cat ~/bin/$1 | sed 's/mkbasic/cpbasic/g' | sed "s/$1/$2/g" > ~/bin/$2 
chmod 755 ~/bin/$2
ln -s ~/bin/$2 "${BASIC}$2"
cat "${BASIC}x_HELP/$1" | sed "s/$1/$2/g" > "${BASIC}x_HELP/$2"
if [ ! -x ~/bin/e ]; then
  echo "created: '$2'"
  echo "Error: 'ln -s _path_to_editor_ ~/bin/e' to set editor"
  exit 4
fi
e ~/bin/$2
e "${BASIC}x_HELP/$2"
exit 0
